workspace = { members = [
    "examples/http-multi-server-channels",
    "examples/http-single-server-channels",
    "examples/iroh-p2p-channels",
    "examples/sql-integration",
] }
[package]
name = "parlay"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
chacha20poly1305 = "0.10.1"
garble_lang = { version = "0.4.0", features = ["serde"] }
rand = "0.8.5"
serde = { version = "1.0.195", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
trait-variant = "0.1.1"
async-trait = "0.1.77"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["async_tokio"] }

[[bench]]
name = "join"
harness = false
