workspace = { members = [
    "examples/http-multi-server-channels",
    "examples/http-single-server-channels",
    "examples/iroh-p2p-channels",
] }
[package]
name = "parlay"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
blake3 = "1.5.0"
chacha20poly1305 = "0.10.1"
garble_lang = "0.2.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
serde = { version = "1.0.195", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
trait-variant = "0.1.1"
async-trait = "0.1.77"

# mpz-ot
futures = "0.3"
rstest = "0.12"
serio = "0.1"

mpz-common = { git = "https://github.com/privacy-scaling-explorations/mpz.git", branch = "ferret-sinu", features = ["test-utils"] }
mpz-ot = { git = "https://github.com/privacy-scaling-explorations/mpz.git", branch = "ferret-sinu", features = ["ideal"] }
mpz-ot-core = { git = "https://github.com/privacy-scaling-explorations/mpz.git", branch = "ferret-sinu" }
mpz-core = { git = "https://github.com/privacy-scaling-explorations/mpz.git", branch = "ferret-sinu" }