name: Cargo Build/Test/Clippy

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: cargo build --verbose
    - run: cargo test --verbose
    - run: cargo clippy -- -Dwarnings
    - run: cargo test
      working-directory: ./examples/http-channels
    - run: cargo test
      working-directory: ./examples/iroh-channels
