name: Cargo Build/Test/Clippy

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo build --release
      - run: cargo bench --no-run
      - run: cargo test --release
      - run: cargo clippy -- -Dwarnings
      - run: cargo build --release && cargo test --release -- --nocapture
        working-directory: ./examples/http-multi-server-channels
      - run: cargo build --release && cargo test --release -- --nocapture
        working-directory: ./examples/http-single-server-channels
      - run: cargo build --release && cargo test --release -- --nocapture
        working-directory: ./examples/iroh-p2p-channels
      - run: docker compose -f docker-compose.yml up -d && cargo build --release && cargo test --release -- --nocapture
        working-directory: ./examples/sql-integration
      - run: cargo build --release && cargo test --release -- --nocapture
        working-directory: ./examples/api-integration
      - run: cargo build --features is_sync --release && cargo test --features is_sync --release -- --nocapture
        working-directory: ./examples/sync-channel
