name: Cargo Build/Test/Clippy

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-ci-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo build --release
      - run: cargo test --release
      - run: cargo clippy --release -- -Dwarnings

  example_multi_server_channels:
    runs-on: ubuntu-latest
    needs: ci
    concurrency:
      group: ${{ github.workflow }}-example_multi_server_channels-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run example http-multi-server-channels
        run: cargo test --release -- --nocapture
        working-directory: ./examples/http-multi-server-channels

  example_single_server_channels:
    runs-on: ubuntu-latest
    needs: ci
    concurrency:
      group: ${{ github.workflow }}-example_single_server_channels-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run example http-single-server-channels
        run: cargo test --release -- --nocapture
        working-directory: ./examples/http-single-server-channels

  example_iroh_p2p_channels:
    runs-on: ubuntu-latest
    needs: ci
    concurrency:
      group: ${{ github.workflow }}-example_iroh_p2p_channels-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run example iroh-p2p-channels
        run: cargo test --release -- --nocapture
        working-directory: ./examples/iroh-p2p-channels

  example_sql_integration:
    runs-on: ubuntu-latest
    needs: ci
    concurrency:
      group: ${{ github.workflow }}-example_sql_integration-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Run example sql-integration
        run: docker compose -f docker-compose.yml up -d && cargo build --release && cargo test --release -- --nocapture
        working-directory: ./examples/sql-integration
